### ISSUE TITLE
geopunt > nog steeds dubbels

### ISSUE THREAD

**Issue by barthanssens** [Informatievlaanderen/vodap#19]
Lembeek-Noord - RUP_20001_213_17001_00001 - PV

Staat er drie keer in
- https://opendata.vlaanderen.be/dataset/lembeek-noord-rup_20001_213_17001_00001-pv120
- https://opendata.vlaanderen.be/dataset/lembeek-noord-rup_20001_213_17001_00001-pv119
- https://opendata.vlaanderen.be/dataset/lembeek-noord-rup_20001_213_17001_00001-pv

**Comment by bertvannuffelen** [comment]
related to #35.

**Comment by bertvannuffelen** [comment]
DSI doet een herimplementatie van hun aanpak en hun dataset publicatie van RUPs.
