### ISSUE TITLE
ckan > ui > admin pagina

### ISSUE THREAD

**Issue by bertvannuffelen** [Informatievlaanderen/vodap#31]
Vervangen   van Engelstalige tekst (gecombineerd met Nederlandstalige) op   https://opendata.vlaanderen.be/ckan-admin door nederlandstalige. NL tekst is bezorgd.

**Comment by pduchesne** [comment]
Can you provide the NL translation please?
The text is "As a sysadmin user you have full control over this CKAN instance. Proceed with care! For guidance on using sysadmin features, see the CKAN sysadmin guide"
