### ISSUE TITLE
CKAN > DCAT compatibel maken van de CKAN GUI > editor

### ISSUE THREAD

**Issue by bertvannuffelen** [Informatievlaanderen/vodap#36]
- Bijkomende invulmogelijkheid voorzien voor velden in in edit-schermen: Thema, geografische dekking, begin+einde geldigheidsperiode, Publicatiedatum, Laatst gewijzigd, Toegangsbeperkingen, Taal. Philippe werkt aanpak uit met testdata
- Aanpassen van de volgorde van velden op view- en editschermen voor datasets en distributies, in overeenstemming met Excel-lijstje. Volgorde nog door te geven door Dirk. Philippe werkt aanpak uit met testdata.

**Comment by bertvannuffelen** [comment]
Getest: nog enkele aanpassingen nodig:

Dataset:

·         Change Label “Organisaties” into “Organisatie”

·         Delete entry bar fo “Uitgever email” (Publisher has no e-mail in DCAT-AP)

·         Change Label “Theme” into “Thema”

·         Add entry bars for “Geldigheidsperiode”: start- and end date/time (= temporal-extent-begin en temporal-extent-end)

·         Add entry bar for “Ruimtelijke dekking” (= extra:spatial_text)

Distributie:

·         Change label “Naam” into “Titel”

·         Add entry bar for “Mediatype” (resource:mimetype)

delete (if possible) entry bars with following labels under “System information”?

“Eigenaar / Contactpunt”
“Auteur Email”
“Beheerder”
“Beheerder Email”

**Comment by OpendataVlaanderen** [comment]
On opendata.dev-vlaanderen.be a record can only be saved if <Maintainer email> has a (valid) value (> CKAN).

**Comment by OpendataVlaanderen** [comment]
On opendata.dev-vlaanderen.be a record can only be saved if <Maintainer Email> has a (valid) value. This value can only be given by a holder of an "admin"-role (a holder of a editor-role has no "System Information"-section. Consequence is that the-dev-environment cannot be used for editor-tests.

**Comment by OpendataVlaanderen** [comment]
On opendata.dev-vlaanderen.be a record can only be saved if (Ckan) Maintainer Email has a (valid) value. This value can only be given by a holder of an "admin"-role (a holder of a editor-role has no "System Information"-section. Consequence is that the-dev-environment cannot be used for editor-tests.
