### ISSUE TITLE
codelijst taal

### ISSUE THREAD

**Issue by bertvannuffelen** [Informatievlaanderen/vodap#4]
Volgens DCAT-AP specificatie wordt de codelijst http://publications.europa.eu/resource/authority/language vereist.

Echter de harversters controleren die waarde niet. Dat geeft dan in de geaggregeerde dcat catalogus voor language a mix van data.

In geonetwerk wordt de ISO639-2  standaard gevolgd.
De geonetwerk DCAT-AP output genereert: <dct:language rdf:resource="http://publications.europa.eu/resource/authority/language/DUT"/>
wat incorrect is, het moet http://publications.europa.eu/resource/authority/language/NLD  zijn.

**Comment by barthanssens** [comment]
Stad Gent gebruikt overigens lexvo (http://lexvo.org/id/iso639-3/nld)

https://opendata.vlaanderen.be/dataset/gentse-feesten-locaties-2018.ttl

**Comment by bertvannuffelen** [comment]
Hierbij hangt ook nog samen:
    * het tonen van de juiste label in CKAN.
