### ISSUE TITLE
Still some dcat:accessURLs using opendataforum.info

### ISSUE THREAD

**Issue by barthanssens** [Informatievlaanderen/vodap#57]
E.g. https://opendata.vlaanderen.be/dataset/speurgids-databank.rdf

`<dcat:accessURL rdf:resource="http://data.opendataforum.info/storage/f/2014-09-01T08%3A19%3A55.670Z/tabel-overzicht-kredietlijnen.xlsx"/>
`
Problem is that the opendataforum.info is not owned by InformatieVlaanderen anymore, and it now points to adult content....

**Comment by bertvannuffelen** [comment]
Philippe, 

de storage functionaliteit, mocht die nog actief zijn mag gedisabled worden. Blijkbaar is er in de config nog een verwijzing naar het oude domein data.opendataforum.info. 

 - [ ] @bertvannuffelen check hoeveel er van deze gevallen zijn.

**Comment by pduchesne** [comment]
De storage functionaliteit is al lang gedisabled, maar enkele oude datasets nog een opendataforum URL hebben (en de werkelijke gegevens zijn natuurlijk niet meer beschikbaar). Wat moet met deze gebeuren? Gewoon verwijderen?

**Comment by bertvannuffelen** [comment]
@pduchesne  gewoon verwijderen

Volgens mij is dit de enige dataset resource die moet verwijderd worden:
```
https://opendata.vlaanderen.be/dataset/72ad6710-36a4-4d75-9f72-703793ef4f7a/resource/2272d8ed-4680-40ed-a498-55d0c4115791
```

**Comment by bertvannuffelen** [comment]
gedaan door Dirk.
