### ISSUE TITLE
Invalid whitespace characters in URLs

### ISSUE THREAD

**Issue by barthanssens** [Informatievlaanderen/vodap#60]
E.g.
http://opendata.vlaanderen.be/catalog.xml?page=105

https://opendata.vlaanderen.be/dataset/605240ec-3121-424f-988e-bdd5f0eab218/resource/da243d7b-9918-4512-a90f-c83c85cc9a81

"http://open-data.europa.eu/data/uploads/MOVE/BE-Agentschap wegen and verkeer.xml" contains whitespaces instead of pct-encoded values

**Comment by bertvannuffelen** [comment]
Dit is een onderdeel van de DCAT-AP VL als gebruiksnota opgenomen. 
identiek aan #52
